model_list:
  - model_name: groq-llama-3-70b
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-llama-3-8b
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-gpt-oss-20b
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-gpt-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-compound-beta-mini
    litellm_params:
      model: groq/compound-beta-mini
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-compound-beta
    litellm_params:
      model: groq/compound-beta
      api_key: "os.environ/GROQ_API_KEY"

#   - model_name: groq-moonshot-kimi-k2
#     litellm_params:
#       model: groq/moonshotai/kimi-k2-instruct
#       api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-meta-llama-4-maverick
    litellm_params:
      model: groq/meta-llama/llama-4-maverick-17b-128e-instruct
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: groq-meta-llama-4-scout
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: "os.environ/GROQ_API_KEY"
